server:
  port: 8080

spring:
  application:
    name: demo-routingdatasource

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres?characterEncoding=UTF-8
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: postgres
        password: ${db-password}
    slave:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/ro-demo?characterEncoding=UTF-8
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: postgres
        password: ${db-password}
